### ISSUE TITLE
Super Confused 

### ISSUE THREAD

**Issue by K-r-n-l** [x0reaxeax/c0wadlina#4]
Hello and thanks for the support I've done everything and can't seem to get this working.                                                                    
I downloaded EFILOADER and placed it on my USB and followed the steps correctly.                                                                      
USB
├── EFI
│   └── Boot
│       └── bootx64.efi
└── memory.efi

Step 3. Disconnect any other storage drives connected to your computer and boot your PC from the USB
Step 4. A 'UEFI Shell' should appear on your screen. If you've disconnected all other USB storage drives, your USB should be labeled fs0. Navigate to it by typing fs0:

This is where I'm lost at, even though i have the USB setup correctly the UEFI Shell does not appear. Can anyone help me out? Sorry if I  sound dumb or this has already been answered but i googled it and couldn't find any relevant information.

**Comment by x0reaxeax** [comment]
Are you positive you're actually booting from the USB?
Can you check if you're running UEFI mode and **not** LEGACY?

**Comment by Crusader420** [comment]
> Are you positive you're actually booting from the USB?
> Can you check if you're running UEFI mode and **not** LEGACY?

Thanks for the quick reply. I checked and I am running Legacy BIOS mode.

**Comment by x0reaxeax** [comment]
You need to switch to **UEFI** mode, otherwise you won't be able to load the UEFI shell :)

**Comment by Crusader420** [comment]
> You need to switch to **UEFI** mode, otherwise you won't be able to load the UEFI shell :)

Okay I understand. So switching  to UEFI mode I would just follow a tutorial like https://www.youtube.com/watch?v=0aRUXQz5ygc
Also with the tutorial I listed above that wont delete any data on the drives correct?

**Comment by x0reaxeax** [comment]
Your machine can't boot a GPT partition when installed in BIOS mode. If your machine doesn't offer a Legacy+UEFI support, you won't be able to boot this.

You can of course convert your MBR partition to GPT, but your Windows installation will need to be repaired via the Windows Instalation Media. This is not a super simple process. 

Just want to make sure, are you aware this tool is outdated and requires manual updating? It'd suck if you've gone through all that trouble, expecting this to work off right away, because it won't.

**Comment by Crusader420** [comment]
> Your machine can't boot a GPT partition when installed in BIOS mode. If your machine doesn't offer a Legacy+UEFI support, you won't be able to boot this.
> 
> You can of course convert your MBR partition to GPT, but your Windows installation will need to be repaired via the Windows Instalation Media. This is not a super simple process.
> 
> Just want to make sure, are you aware this tool is outdated and requires manual updating? It'd suck if you've gone through all that trouble, expecting this to work off right away, because it won't.

I know it is outdated and requires updating. I was just having problems setting up this side of everything. I changed my MBR partition to GPT and my windows didn't need to be repaired. It now says UEFI as the Boot mode, Secure boot state is unsupported though don't know if that means anything. Does this mean I'm able to use this now that I am in UEFI mode? What file system does the USB have to be I'm guessing Fat32? Again thank you for your help.

**Comment by x0reaxeax** [comment]
Oh, perfect! Yes, you should be able to boot to the shell now :)

No problem, let me know if you got it working :)

**Comment by Crusader420** [comment]
> Oh, perfect! Yes, you should be able to boot to the shell now :)
> 
> No problem, let me know if you got it working :)

So I did Step 3 again : 

USB
├── EFI
│ └── Boot
│ └── bootx64.efi
└── memory.efi

Tried to boot into it and it just got stuck at Verifying DMI pool. Could this be a issue with the USB being the wrong File System / Partition Scheme? I chose Boot selection as Non bootable, I'm thinking that is the issue. GTP and NTFS as File System and Partition Scheme.

**Comment by x0reaxeax** [comment]
I'm not positive, but it might be. Format your USB with FAT32. Also make sure your Secure Boot is still disabled, and if that's not an option, try adding the UEFI shell EFI loader (bootx64.efi) to the Secure Boot whitelist.

**Comment by K-r-n-l** [comment]
> I'm not positive, but it might be. Format your USB with FAT32. Also make sure your Secure Boot is still disabled, and if that's not an option, try adding the UEFI shell EFI loader (bootx64.efi) to the Secure Boot whitelist.

I have no option to enable or disable secure boot in my bios, when i bring up System Information it says Secure boot unsuportted. It's weird cause i see the USB but it just wont let me boot onto it. 

So just to make sure GTP / FAT32
extract edk2 efi shell to /EFI/Boot/bootx64.efi
leave the memory.efi in root directory then i should be able to boot the shell from the usb?
Might just be cause I have super old BIOS or something. I even changed to EFI mode in bios to no avail. 
Might just have to wait until I get my new computer.

**Comment by K-r-n-l** [comment]
> > I'm not positive, but it might be. Format your USB with FAT32. Also make sure your Secure Boot is still disabled, and if that's not an option, try adding the UEFI shell EFI loader (bootx64.efi) to the Secure Boot whitelist.
> 
> I have no option to enable or disable secure boot in my bios, when i bring up System Information it says Secure boot unsupported. Also my BIOS mode says uefi. It's weird cause i see the USB but it just wont let me boot onto it.
> 
> So just to make sure GTP / FAT32
> extract edk2 efi shell to /EFI/Boot/bootx64.efi
> leave the memory.efi in root directory then i should be able to boot the shell from the usb?
> Might just be cause I have super old BIOS or something. I even changed to EFI mode in bios to no avail.
> Might just have to wait until I get my new computer.

**Comment by x0reaxeax** [comment]
Well, since your Windows 10 boots in UEFI mode, it has to boot Windows' `bootmgfw.efi`. Maybe a very ugly hack would be to replace this Windows' boot manager EFI with the UEFI shell itself and boot the bootmgr from the shell later.

So for example, you'd rename `bootmgfw.efi` in ESP system partition to `dont_bootmgfw.efi`, place the edk2 shell to the same directory and name it `bootmgfw.efi`.

Then if it boots, you could just do `$: dont_bootmgfw.efi` to boot to Windows.

**Comment by K-r-n-l** [comment]
> Well, since your Windows 10 boots in UEFI mode, it has to boot Windows' `bootmgfw.efi`. Maybe a very ugly hack would be to replace this Windows' boot manager EFI with the UEFI shell itself and boot the bootmgr from the shell later.
> 
> So for example, you'd rename `bootmgfw.efi` in ESP system partition to `dont_bootmgfw.efi`, place the edk2 shell to the same directory and name it `bootmgfw.efi`.
> 
> Then if it boots, you could just do `$: dont_bootmgfw.efi` to boot to Windows.

Holy shit so I did what you told me, got the shell working. I couldn't load back into windows though using the old boot manager efi. Thinking its cause I didnt copy bootmgfw.efi. Gonna have to learn how to copy it from the shell to FS0 because I'm stuck in shell now cant boot windows.

**Comment by x0reaxeax** [comment]
Perfect, we know that your machine is capable of booting the shell!

You can use the `map` command to list available devices and their paths.
Your ESP partition may be `fs1:` or something similar, maybe you can dump the info for me? ( a picture would be sufficient )

Alternatively, just leave the `memory.efi` loader in the same folder as your bootmgr.

**Comment by K-r-n-l** [comment]
> Perfect, we know that your machine is capable of booting the shell!
> 
> You can use the `map` command to list available devices and their paths.
> Your ESP partition may be `fs1:` or something similar, maybe you can dump the info for me? ( a picture would be sufficient )
> 
> Alternatively, just leave the `memory.efi` loader in the same folder as your bootmgr.
> 
> EDIT:
> Perfect, I'm glad to hear that!
> 
> You're very welcome, thank you very much for your info too!
> 
> Since we know your machine is capable of booting the shell, maybe booting the USB itself is the actual problem here. You could try burning the files to a CD/DVD and try booting it.

Unfortunately I dont 

> Perfect, we know that your machine is capable of booting the shell!
> 
> You can use the `map` command to list available devices and their paths.
> Your ESP partition may be `fs1:` or something similar, maybe you can dump the info for me? ( a picture would be sufficient )
> 
> Alternatively, just leave the `memory.efi` loader in the same folder as your bootmgr.
> 
> EDIT:
> Perfect, I'm glad to hear that!
> 
> You're very welcome, thank you very much for your info too!
> 
> Since we know your machine is capable of booting the shell, maybe booting the USB itself is the actual problem here. You could try burning the files to a CD/DVD and try booting it.

Honestly I think booting like this would be fine, as the USB way dont work for me always have the shell popup at boot and then manually load into windows with the efi if that's possible. 

I noticed how you stated Then if it boots, you could just do $: dont_bootmgfw.efi to boot to Windows but my original bootmgfw.efi is either named something else or I cannot find it. Mind letting me know where I could find the correct efi to boot to windows from the shell?

**Comment by x0reaxeax** [comment]
Amazing! You're very welcome buddy, I'm happy you got it working and shared your info/steps here, thank you very much for that!
